language: generic

services:
  - docker

before_install:
  - docker-compose -f docker/docker-compose.$CURRENT_ADAPTER.yml build spec

script:
  - docker-compose -f docker/docker-compose.$CURRENT_ADAPTER.yml run spec

matrix:
  include:
    - name: "Mysql 5.7"
      env:
        - CURRENT_ADAPTER=mysql
        - MYSQL_VERSION=5.7
        - PG_VERSION=10.5
    - name: "Mysql 5.6"
      env:
        - CURRENT_ADAPTER=mysql
        - MYSQL_VERSION=5.6
        - PG_VERSION=10.5
    - name: "Postgres 9.6"
      env:
        - CURRENT_ADAPTER=pg
        - MYSQL_VERSION=5.7
        - PG_VERSION=9.6
    - name: "Postgres 10.5"
      env:
        - CURRENT_ADAPTER=pg
        - MYSQL_VERSION=5.7
        - PG_VERSION=10.5
    - name: "Postgres 11"
      env:
        - CURRENT_ADAPTER=pg
        - MYSQL_VERSION=5.7
        - PG_VERSION=11
    - name: "Sqlite 3.11.0"
      env:
        - CURRENT_ADAPTER=sqlite
        - MYSQL_VERSION=5.7
        - PG_VERSION=10.5
        - SQLITE_VERSION=3110000
        - SQLITE_VERSION_YEAR=2016
    - name: "Sqlite 3.25.2"
      env:
        - CURRENT_ADAPTER=sqlite
        - MYSQL_VERSION=5.7
        - PG_VERSION=10.5
        - SQLITE_VERSION=3250200
        - SQLITE_VERSION_YEAR=2018
